CREATE TABLE tipoAlumno (
	id_tipo BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
	detalle VARCHAR (60)  NOT NULL,
	islocked BOOLEAN NULL,
	Monto INTEGER,
	PRIMARY KEY (id_tipo)	
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;